version: '3'
services:
  # App services
  todo-backend:
    container_name: todo-backend
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mysql-db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules

  # Database services
  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_OS_PORT}:${MYSQL_DOCKER_PORT}
      